spring.data.mongodb.uri=uri: mongodb+srv://vinayakswain49_db_user:mongodb@cluster0.rkecvg0.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true