spring.data.mongodb.uri=mongodb+srv://vinayakswain49_db_user:vinayak1809@cluster0.rkecvg0.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true